version: '3'
services:

  db:
    image: postgres:9.5
    restart: always
    volumes:
      - mahara_db:/var/lib/postgresql/data/
      - ./db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - /home/tmteam/mahara/dbdump.sql:/tmp/dbdump.sql
      - ./conf/postgresql.conf:/etc/postgresql.conf
      # import db
      # - ./db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      # - /home/tmteam/mahara/dbdump.sql:/tmp/dbdump.sql

    command: -c config_file=/etc/postgresql.conf
    environment:
      - POSTGRES_USER=mahara
      - POSTGRES_PASSWORD=mahara
      - POSTGRES_DB=maharadb

  web:
    build: ./
    restart: always
    volumes:
      - mahara:/var/www/html
      - mahara_data:/opt/dataroot
      - ./conf/php-fpm.conf:/etc/php/7.0/fpm/php-fpm.conf
      - ./conf/php.ini:/etc/php/7.0/fpm/php.ini
    links:
      - db:dbhost

  nginx-proxy:
    restart: always
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - mahara:/var/www/html
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
    depends_on:
      - web

volumes:
  mahara:
    driver: local-persist
    driver_opts:
      mountpoint: /home/tmteam/mahara/mahara-src
  mahara_data:
    driver: local-persist
    driver_opts:
      mountpoint: /home/tmteam/mahara/mahara-data
  mahara_db:
    driver: local-persist
    driver_opts:
      mountpoint: /home/tmteam/mahara/mahara-db
